#!/usr/bin/env ruby

require File.expand_path(File.join(File.expand_path(__FILE__), "..", "..", "lib", "convoy"))
require File.join(File.expand_path(__FILE__), "..", "commands", "example_command")

Convoy::App.create do |app|
    app.requires_arguments

    app.options do |opts|
        opts.opt :option1, "Option1", :short => '-o', :long => '--option1', :type => :string, :default => "option 1"
        opts.opt :option2, "Option2", :short => :none, :long => '--option2', :type => :string, :multi => true
    end

    app.action do |options, arguments|
        Convoy::ExampleCommand.new(options, arguments).execute
    end
end
