#!/usr/bin/env ruby

require File.expand_path(File.join(File.expand_path(__FILE__), "..", "..", "lib", "convoy"))
require File.join(File.expand_path(__FILE__), "..", "commands", "example_command")

Convoy::App.create do |app|
  app.command :command1, :aliases => [:c1, :com1]  do |command|
    command.summary "Command summary 1"
    command.description "Command description 1"

    command.action do |options, arguments|
      Convoy::ExampleCommand.new(options, arguments).execute
    end
  end

  app.action do |options, arguments|
    Convoy::ExampleCommand.new(options, arguments).execute
  end
end
